import { Bahiana, Marhey } from "next/font/google";

import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

const marhey = Marhey({
  variable: "--font-geist-sans",
  weight: ["400"],
  subsets: ["latin"],
});

const bahiana = Bahiana({
  variable: "--font-geist-sans",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marhey.variable} ${bahiana.variable} antialiased`}
      >
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
            <Toaster richColors position="top-right" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
